#!/bin/bash

export DATE=`date --iso-8601`;

echo "Dumping breedbase db, $DATE";

rm $HOME/.pgpass

echo "breedbase_db:5432:breedbase:postgres:postgres"> $HOME/.pgpass

chmod 0600 $HOME/.pgpass

ls -al $HOME/.pgpass

pg_dump -h breedbase_db -U postgres -w -d breedbase > /db_dumps/breedbase_$DATE.sql

